const fs = require('fs');

const partnerSettingsLangs = {
  en: { title: "Profile Settings", back: "← Back to Dashboard", themeLabel: "Appearance Theme", langLabel: "Language", currLabel: "Currency", cardLabel: "Payment Methods", cardBound: "Active Payment Details", cardUnbound: "No card bound. Payouts are suspended.", btnUnbind: "Unbind Card", btnBind: "Bind New Card", btnSave: "Save Changes", success: "Settings updated successfully!", themes: { dark: "Dark", light: "Light" }, verificationTitle: "Verification Status", verificationLock: "Verification is locked. Complete 100+ deals to apply.", verificationCurrent: "Completed Deals Progress", btnSimulate: "Simulate 105 Deals", btnApply: "Request Verification ✅", statusPending: "Verification request is pending review.", statusVerified: "Your profile is officially verified!" },
  ru: { title: "Настройки профиля", back: "← Назад в панель", themeLabel: "Тема оформления", langLabel: "Язык", currLabel: "Валюта", cardLabel: "Способы оплаты", cardBound: "Активные реквизиты", cardUnbound: "Карта не привязана. Выплаты приостановлены.", btnUnbind: "Отвязать карту", btnBind: "Привязать новую карту", btnSave: "Сохранить изменения", success: "Настройки успешно обновлены!", themes: { dark: "Темная", light: "Светлая" }, verificationTitle: "Статус верификации", verificationLock: "Верификация заблокирована. Завершите 100+ сделок.", verificationCurrent: "Прогресс завершенных сделок", btnSimulate: "Симулировать 105 сделок", btnApply: "Запросить верификацию ✅", statusPending: "Запрос на верификацию на рассмотрении.", statusVerified: "Ваш профиль официально верифицирован!" },
  id: { title: "Pengaturan Profil", back: "← Kembali ke Dasbor", themeLabel: "Tema Tampilan", langLabel: "Bahasa", currLabel: "Mata Uang", cardLabel: "Metode Pembayaran", cardBound: "Detail Pembayaran Aktif", cardUnbound: "Tidak ada kartu terikat. Pembayaran ditangguhkan.", btnUnbind: "Lepas Kartu", btnBind: "Ikat Kartu Baru", btnSave: "Simpan Perubahan", success: "Pengaturan berhasil diperbarui!", themes: { dark: "Gelap", light: "Terang" }, verificationTitle: "Status Verifikasi", verificationLock: "Verifikasi terkunci. Selesaikan 100+ kesepakatan.", verificationCurrent: "Kemajuan Kesepakatan Selesai", btnSimulate: "Simulasikan 105 Kesepakatan", btnApply: "Minta Verifikasi ✅", statusPending: "Permintaan verifikasi sedang ditinjau.", statusVerified: "Profil Anda resmi terverifikasi!" },
  zh: { title: "个人资料设置", back: "← 返回仪表板", themeLabel: "外观主题", langLabel: "语言", currLabel: "货币", cardLabel: "付款方式", cardBound: "有效付款信息", cardUnbound: "未绑定银行卡。付款已暂停。", btnUnbind: "解绑银行卡", btnBind: "绑定新卡", btnSave: "保存更改", success: "设置更新成功！", themes: { dark: "深色", light: "浅色" }, verificationTitle: "验证状态", verificationLock: "验证已锁定。完成 100 笔以上交易以申请。", verificationCurrent: "已完成交易进度", btnSimulate: "模拟 105 笔交易", btnApply: "请求验证 ✅", statusPending: "验证请求正在审核中。", statusVerified: "您的个人资料已正式验证！" },
  es: { title: "Configuración del Perfil", back: "← Volver al Panel", themeLabel: "Tema de Apariencia", langLabel: "Idioma", currLabel: "Moneda", cardLabel: "Métodos de Pago", cardBound: "Detalles de Pago Activos", cardUnbound: "No hay tarjeta vinculada. Pagos suspendidos.", btnUnbind: "Desvincular Tarjeta", btnBind: "Vincular Nueva Tarjeta", btnSave: "Guardar Cambios", success: "¡Configuración actualizada con éxito!", themes: { dark: "Oscuro", light: "Claro" }, verificationTitle: "Estado de Verificación", verificationLock: "Verificación bloqueada. Completa más de 100 acuerdos.", verificationCurrent: "Progreso de Acuerdos Completados", btnSimulate: "Simular 105 Acuerdos", btnApply: "Solicitar Verificación ✅", statusPending: "La solicitud de verificación está en revisión.", statusVerified: "¡Tu perfil está verificado oficialmente!" },
  de: { title: "Profileinstellungen", back: "← Zurück zum Dashboard", themeLabel: "Design", langLabel: "Sprache", currLabel: "Währung", cardLabel: "Zahlungsmethoden", cardBound: "Aktive Zahlungsdetails", cardUnbound: "Keine Karte gebunden. Auszahlungen sind ausgesetzt.", btnUnbind: "Karte entbinden", btnBind: "Neue Karte binden", btnSave: "Änderungen speichern", success: "Einstellungen erfolgreich aktualisiert!", themes: { dark: "Dunkel", light: "Hell" }, verificationTitle: "Verifizierungsstatus", verificationLock: "Verifizierung gesperrt. Schließen Sie 100+ Deals ab.", verificationCurrent: "Fortschritt abgeschlossener Deals", btnSimulate: "105 Deals simulieren", btnApply: "Verifizierung anfordern ✅", statusPending: "Verifizierungsanfrage wird geprüft.", statusVerified: "Ihr Profil ist offiziell verifiziert!" },
  fr: { title: "Paramètres du Profil", back: "← Retour au Tableau de Bord", themeLabel: "Thème", langLabel: "Langue", currLabel: "Devise", cardLabel: "Méthodes de Paiement", cardBound: "Détails de Paiement Actifs", cardUnbound: "Aucune carte liée. Les paiements sont suspendus.", btnUnbind: "Délier la Carte", btnBind: "Lier une Nouvelle Carte", btnSave: "Enregistrer les Modifications", success: "Paramètres mis à jour avec succès !", themes: { dark: "Sombre", light: "Clair" }, verificationTitle: "Statut de Vérification", verificationLock: "Vérification verrouillée. Complétez plus de 100 accords.", verificationCurrent: "Progression des Accords Terminés", btnSimulate: "Simuler 105 Accords", btnApply: "Demander la Vérification ✅", statusPending: "La demande de vérification est en cours d'examen.", statusVerified: "Votre profil est officiellement vérifié !" },
  ja: { title: "プロファイル設定", back: "← ダッシュボードに戻る", themeLabel: "外観テーマ", langLabel: "言語", currLabel: "通貨", cardLabel: "支払い方法", cardBound: "有効な支払い詳細", cardUnbound: "カードがバインドされていません。支払いは一時停止されています。", btnUnbind: "カードのバインド解除", btnBind: "新しいカードをバインド", btnSave: "変更を保存", success: "設定が正常に更新されました！", themes: { dark: "ダーク", light: "ライト" }, verificationTitle: "確認ステータス", verificationLock: "確認がロックされています。申請するには100件以上の取引を完了してください。", verificationCurrent: "完了した取引の進行状況", btnSimulate: "105件の取引をシミュレート", btnApply: "確認をリクエスト ✅", statusPending: "確認リクエストは審査中です。", statusVerified: "あなたのプロファイルは正式に確認されました！" },
  ar: { title: "إعدادات الملف الشخصي", back: "← العودة إلى لوحة التحكم", themeLabel: "سمة المظهر", langLabel: "اللغة", currLabel: "العملة", cardLabel: "طرق الدفع", cardBound: "تفاصيل الدفع النشطة", cardUnbound: "لا توجد بطاقة مقيدة. العوائد معلقة.", btnUnbind: "إلغاء ربط البطاقة", btnBind: "ربط بطاقة جديدة", btnSave: "حفظ التغييرات", success: "تم تحديث الإعدادات بنجاح!", themes: { dark: "داكن", light: "فاتح" }, verificationTitle: "حالة التحقق", verificationLock: "التحقق مقفل. أكمل 100+ صفقات للتقديم.", verificationCurrent: "تقدم الصفقات المكتملة", btnSimulate: "محاكاة 105 صفقات", btnApply: "طلب التحقق ✅", statusPending: "طلب التحقق قيد المراجعة.", statusVerified: "تم التحقق من ملفك الشخصي رسميًا!" },
  pt: { title: "Configurações do Perfil", back: "← Voltar ao Painel", themeLabel: "Tema de Aparência", langLabel: "Idioma", currLabel: "Moeda", cardLabel: "Métodos de Pagamento", cardBound: "Detalhes de Pagamento Ativos", cardUnbound: "Nenhuma cartão vinculado. Os pagamentos estão suspensos.", btnUnbind: "Desvincular Cartão", btnBind: "Vincular Novo Cartão", btnSave: "Salvar Alterações", success: "Configurações atualizadas com sucesso!", themes: { dark: "Escuro", light: "Claro" }, verificationTitle: "Status de Verificação", verificationLock: "Verificação bloqueada. Complete 100+ acordos para solicitar.", verificationCurrent: "Progresso de Acordos Concluídos", btnSimulate: "Simular 105 Acordos", btnApply: "Solicitar Verificação ✅", statusPending: "A solicitação de verificação está sob análise.", statusVerified: "O seu perfil está oficialmente verificado!" },
  hi: { title: "प्रोफ़ाइल सेटिंग", back: "← डैशबोर्ड पर वापस", themeLabel: "प्रकटन थीम", langLabel: "भाषा", currLabel: "मुद्रा", cardLabel: "भुगतान की विधियां", cardBound: "सक्रिय भुगतान विवरण", cardUnbound: "कोई कार्ड बाध्य नहीं। भुगतान निलंबित हैं।", btnUnbind: "कार्ड अनबाइंड करें", btnBind: "नया कार्ड बाइंड करें", btnSave: "परिवर्तन सहेजें", success: "सेटिंग सफलतापूर्वक अपडेट की गई!", themes: { dark: "गहरा", light: "हल्का" }, verificationTitle: "सत्यापन स्थिति", verificationLock: "सत्यापन लॉक है। आवेदन करने के लिए 100+ सौदे पूरे करें।", verificationCurrent: "पूरे किए गए सौदों की प्रगति", btnSimulate: "105 सौदों का अनुकरण करें", btnApply: "सत्यापन का अनुरोध करें ✅", statusPending: "सत्यापन अनुरोध समीक्षा के अधीन है।", statusVerified: "आपकी प्रोफ़ाइल आधिकारिक तौर पर सत्यापित है!" }
};

const onboardingLangs = {
  en: { title: "Welcome to Agent Core", subtitle: "Let's set up your billing profile", langLabel: "Preferred Language", currLabel: "Preferred Currency", cardLabel: "Credit / Debit Card (For Payouts & Reserves)", cardHolder: "Card Number", cardExpiry: "MM/YY", cardCvc: "CVC", btnNext: "Next Step", btnSubmit: "Complete Registration", errorCard: "Please enter a valid card number", success: "Profile configured successfully!", step1: "Step 1: Settings", step2: "Step 2: Payment Card", step3: "Step 3: Contacts", secured: "Secure 256-bit SSL encryption", emailLabel: "Email Address", phoneLabel: "Phone Number", emailPlaceholder: "you@example.com", phonePlaceholder: "+1 (555) 000-0000", contactTitle: "Contact Information" },
  ru: { title: "Добро пожаловать в Agent Core", subtitle: "Давайте настроим платежный профиль", langLabel: "Предпочитаемый язык", currLabel: "Предпочитаемая валюта", cardLabel: "Кредитная / Дебетовая карта", cardHolder: "Номер карты", cardExpiry: "ММ/ГГ", cardCvc: "CVC", btnNext: "Следующий шаг", btnSubmit: "Завершить регистрацию", errorCard: "Пожалуйста, введите действительный номер карты", success: "Профиль успешно настроен!", step1: "Шаг 1: Настройки", step2: "Шаг 2: Карта оплаты", step3: "Шаг 3: Контакты", secured: "Безопасное 256-битное шифрование SSL", emailLabel: "Электронная почта", phoneLabel: "Номер телефона", emailPlaceholder: "you@example.com", phonePlaceholder: "+7 (999) 000-00-00", contactTitle: "Контактная информация" },
  id: { title: "Selamat datang di Agent Core", subtitle: "Mari atur profil penagihan Anda", langLabel: "Bahasa Pilihan", currLabel: "Mata Uang Pilihan", cardLabel: "Kartu Kredit / Debit", cardHolder: "Nomor Kartu", cardExpiry: "BB/TT", cardCvc: "CVC", btnNext: "Langkah Selanjutnya", btnSubmit: "Selesaikan Pendaftaran", errorCard: "Masukkan nomor kartu yang valid", success: "Profil berhasil dikonfigurasi!", step1: "Langkah 1: Pengaturan", step2: "Langkah 2: Kartu Pembayaran", step3: "Langkah 3: Kontak", secured: "Enkripsi SSL 256-bit yang aman", emailLabel: "Alamat Email", phoneLabel: "Nomor Telepon", emailPlaceholder: "anda@contoh.com", phonePlaceholder: "+62 812-3456-7890", contactTitle: "Informasi Kontak" },
  zh: { title: "欢迎来到 Agent Core", subtitle: "让我们设置您的账单档案", langLabel: "首选语言", currLabel: "首选货币", cardLabel: "信用卡/借记卡", cardHolder: "卡号", cardExpiry: "月/年", cardCvc: "安全码(CVC)", btnNext: "下一步", btnSubmit: "完成注册", errorCard: "请输入有效的卡号", success: "档案配置成功！", step1: "步骤 1：设置", step2: "步骤 2：付款卡", step3: "步骤 3：联系方式", secured: "安全的 256 位 SSL 加密", emailLabel: "电子邮件地址", phoneLabel: "电话号码", emailPlaceholder: "you@example.com", phonePlaceholder: "+86 138 0000 0000", contactTitle: "联系信息" },
  es: { title: "Bienvenido a Agent Core", subtitle: "Configuremos su perfil de facturación", langLabel: "Idioma Preferido", currLabel: "Moneda Preferida", cardLabel: "Tarjeta de Crédito / Débito", cardHolder: "Número de Tarjeta", cardExpiry: "MM/AA", cardCvc: "CVC", btnNext: "Siguiente Paso", btnSubmit: "Completar Registro", errorCard: "Por favor ingrese un número de tarjeta válido", success: "¡Perfil configurado con éxito!", step1: "Paso 1: Ajustes", step2: "Paso 2: Tarjeta de Pago", step3: "Paso 3: Contactos", secured: "Cifrado SSL seguro de 256 bits", emailLabel: "Correo Electrónico", phoneLabel: "Número de Teléfono", emailPlaceholder: "usted@ejemplo.com", phonePlaceholder: "+34 600 000 000", contactTitle: "Información de Contacto" },
  de: { title: "Willkommen bei Agent Core", subtitle: "Richten wir Ihr Rechnungsprofil ein", langLabel: "Bevorzugte Sprache", currLabel: "Bevorzugte Währung", cardLabel: "Kredit- / Debitkarte", cardHolder: "Kartennummer", cardExpiry: "MM/JJ", cardCvc: "CVC", btnNext: "Nächster Schritt", btnSubmit: "Registrierung abschließen", errorCard: "Bitte geben Sie eine gültige Kartennummer ein", success: "Profil erfolgreich konfiguriert!", step1: "Schritt 1: Einstellungen", step2: "Schritt 2: Zahlungskarte", step3: "Schritt 3: Kontakte", secured: "Sichere 256-Bit-SSL-Verschlüsselung", emailLabel: "E-Mail-Adresse", phoneLabel: "Telefonnummer", emailPlaceholder: "sie@beispiel.de", phonePlaceholder: "+49 170 1234567", contactTitle: "Kontaktinformationen" },
  fr: { title: "Bienvenue sur Agent Core", subtitle: "Configurons votre profil de facturation", langLabel: "Langue Préférée", currLabel: "Devise Préférée", cardLabel: "Carte de Crédit / Débit", cardHolder: "Numéro de Carte", cardExpiry: "MM/AA", cardCvc: "CVC", btnNext: "Étape Suivante", btnSubmit: "Terminer l'Inscription", errorCard: "Veuillez entrer un numéro de carte valide", success: "Profil configuré avec succès !", step1: "Étape 1 : Paramètres", step2: "Étape 2 : Carte de Paiement", step3: "Étape 3 : Contacts", secured: "Cryptage SSL 256 bits sécurisé", emailLabel: "Adresse E-mail", phoneLabel: "Numéro de Téléphone", emailPlaceholder: "vous@exemple.fr", phonePlaceholder: "+33 6 12 34 56 78", contactTitle: "Informations de Contact" },
  ja: { title: "Agent Core へようこそ", subtitle: "請求プロファイルを設定しましょう", langLabel: "希望の言語", currLabel: "希望の通貨", cardLabel: "クレジット / デビットカード", cardHolder: "カード番号", cardExpiry: "月/年", cardCvc: "CVC", btnNext: "次のステップ", btnSubmit: "登録を完了する", errorCard: "有効なカード番号を入力してください", success: "プロファイルが正常に構成されました！", step1: "ステップ 1: 設定", step2: "ステップ 2: 支払いカード", step3: "ステップ 3: 連絡先", secured: "安全な256ビットSSL暗号化", emailLabel: "メールアドレス", phoneLabel: "電話番号", emailPlaceholder: "you@example.com", phonePlaceholder: "+81 90-1234-5678", contactTitle: "連絡先情報" },
  ar: { title: "مرحبا بك في Agent Core", subtitle: "دعنا نعد ملف تعريف الفواتير الخاص بك", langLabel: "اللغة المفضلة", currLabel: "العملة المفضلة", cardLabel: "بطاقة الائتمان / الخصم", cardHolder: "رقم البطاقة", cardExpiry: "شهر/سنة", cardCvc: "رمز الأمان", btnNext: "الخطوة التالية", btnSubmit: "إكمال التسجيل", errorCard: "الرجاء إدخال رقم بطاقة صالح", success: "تم تكوين الملف الشخصي بنجاح!", step1: "الخطوة 1: الإعدادات", step2: "الخطوة 2: بطاقة الدفع", step3: "الخطوة 3: جهات الاتصال", secured: "تشفير SSL آمن 256 بت", emailLabel: "عنوان البريد الإلكتروني", phoneLabel: "رقم الهاتف", emailPlaceholder: "you@example.com", phonePlaceholder: "+971 50 123 4567", contactTitle: "معلومات الاتصال" },
  pt: { title: "Bem-vindo ao Agent Core", subtitle: "Vamos configurar o seu perfil de faturação", langLabel: "Idioma Preferido", currLabel: "Moeda Preferida", cardLabel: "Cartão de Crédito / Débito", cardHolder: "Número do Cartão", cardExpiry: "MM/AA", cardCvc: "CVC", btnNext: "Próximo Passo", btnSubmit: "Concluir Registo", errorCard: "Por favor, insira um número de cartão válido", success: "Perfil configurado com sucesso!", step1: "Passo 1: Configurações", step2: "Passo 2: Cartão de Pagamento", step3: "Passo 3: Contactos", secured: "Criptografia SSL de 256 bits segura", emailLabel: "Endereço de E-mail", phoneLabel: "Número de Telefone", emailPlaceholder: "voce@exemplo.pt", phonePlaceholder: "+351 912 345 678", contactTitle: "Informações de Contacto" },
  hi: { title: "एजेंट कोर में आपका स्वागत है", subtitle: "आइए अपनी बिलिंग प्रोफ़ाइल सेट करें", langLabel: "पसंदीदा भाषा", currLabel: "पसंदीदा मुद्रा", cardLabel: "क्रेडिट / डेबिट कार्ड", cardHolder: "कार्ड नंबर", cardExpiry: "एमएम/वाईवाई", cardCvc: "सीवीसी", btnNext: "अगला कदम", btnSubmit: "पंजीकरण पूर्ण करें", errorCard: "कृपया एक मान्य कार्ड नंबर दर्ज करें", success: "प्रोफ़ाइल सफलतापूर्वक कॉन्फ़िगर की गई!", step1: "चरण 1: सेटिंग्स", step2: "चरण 2: भुगतान कार्ड", step3: "चरण 3: संपर्क", secured: "सुरक्षित 256-बिट एसएसएल एन्क्रिप्शन", emailLabel: "ईमेल पता", phoneLabel: "फ़ोन नंबर", emailPlaceholder: "you@example.com", phonePlaceholder: "+91 98765 43210", contactTitle: "संपर्क जानकारी" }
};

const businessLangs = {
  en: {
    venue: "Venue Manager", exit: "Exit", settings: "Settings ⚙️", balanceLabel: "Active Reserve Balance", depositBtn: "Deposit $100", reserveNote: "🔒 Reserve Protection Active: Offers will automatically de-activate if reward amount exceeds your current reserve balance.", attributeTitle: "Attribute Referral Code", verifyBtn: "Verify & Pay", offersTitle: "Your Active Offers", rewardLabel: "Reward", statusActive: "ACTIVE", statusPaused: "PAUSED (Low Balance)", noOffers: "No offers created yet", noTransactions: "No transactions recorded yet", createTitle: "Create New Offer", offerTitleLabel: "Offer Title", offerTitlePlaceholder: "e.g. Special Promotion", categoryLabel: "Category", rewardTypeLabel: "Reward Type", fixedReward: "Fixed Amount", percentageReward: "Percentage of Bill", rewardAmountLabel: "Promoter Reward Amount (in USD)", avgBillLabel: "Average Bill (in USD)", percentLabel: "Reward Percentage (%)", conditionsLabel: "Conditions / Description", conditionsPlaceholder: "Describe conversion terms (e.g. purchase of main dish is required)", createBtn: "Create Offer", cancelBtn: "Cancel", codeError: "Active referral code not found or expired", offerError: "Offer not found", balanceError: "Insufficient reserve balance to pay the reward", balanceErrorCreate: "Insufficient reserve balance to cover the reward. Please deposit funds first.", successPrefix: "Referral confirmed!", depositSuccess: "successfully added to your reserve balance.", loading: "Loading Business Portal...", recentTransactions: "Recent Transactions",
    categories: { restaurant: "Restaurant", nightlife: "Nightlife", real_estate: "Real Estate & Villas", beauty: "Beauty & Spa", fitness: "Fitness & Sports", retail: "Retail", activity: "Activities", services: "Services" }
  },
  ru: {
    venue: "Менеджер заведения", exit: "Выйти", settings: "Настройки ⚙️", balanceLabel: "Активный баланс резерва", depositBtn: "Пополнить на $100", reserveNote: "🔒 Защита резервов активна: офферы автоматически отключаются, если сумма награды превышает текущий баланс резерва.", attributeTitle: "Подтвердить реферальный код", verifyBtn: "Проверить и выплатить", offersTitle: "Ваши активные предложения", rewardLabel: "Награда", statusActive: "АКТИВЕН", statusPaused: "ПАУЗА (Низкий баланс)", noOffers: "Офферы еще не созданы", noTransactions: "Транзакции пока отсутствуют", createTitle: "Создать новое предложение", offerTitleLabel: "Название предложения", offerTitlePlaceholder: "например, Специальное предложение", categoryLabel: "Категория", rewardTypeLabel: "Тип вознаграждения", fixedReward: "Фиксированная сумма", percentageReward: "Процент от чека", rewardAmountLabel: "Сумма награды промоутеру (в USD)", avgBillLabel: "Средний чек (в USD)", percentLabel: "Процент вознаграждения (%)", conditionsLabel: "Условия / Описание", conditionsPlaceholder: "Опишите условия конверсии (например, обязательна покупка горячего блюда)", createBtn: "Создать предложение", cancelBtn: "Отмена", codeError: "Активный реферальный код не найден или истек", offerError: "Предложение не найдено", balanceError: "Недостаточно средств в резерве для выплаты награды", balanceErrorCreate: "Недостаточно средств на балансе резерва для создания предложения. Пожалуйста, пополните баланс.", successPrefix: "Реферал подтвержден!", depositSuccess: "успешно добавлено к вашему балансу резерва.", loading: "Загрузка портала бизнеса...", recentTransactions: "Последние транзакции",
    categories: { restaurant: "Ресторан", nightlife: "Ночная жизнь", real_estate: "Недвижимость и Виллы", beauty: "Красота и Спа", fitness: "Фитнес и Спорт", retail: "Ритейл", activity: "Развлечения", services: "Услуги" }
  },
  id: {
    venue: "Manajer Tempat", exit: "Keluar", settings: "Pengaturan ⚙️", balanceLabel: "Saldo Cadangan Aktif", depositBtn: "Setor $100", reserveNote: "🔒 Perlindungan Cadangan Aktif: Penawaran akan dinonaktifkan secara otomatis jika jumlah hadiah melebihi saldo cadangan Anda saat ini.", attributeTitle: "Atribusikan Kode Rujukan", verifyBtn: "Verifikasi & Bayar", offersTitle: "Penawaran Aktif Anda", rewardLabel: "Hadiah", statusActive: "AKTIF", statusPaused: "DITANGGUHKAN (Saldo Rendah)", noOffers: "Belum ada penawaran yang dibuat", noTransactions: "Belum ada transaksi yang tercatat", createTitle: "Buat Penawaran Baru", offerTitleLabel: "Judul Penawaran", offerTitlePlaceholder: "mis. Promosi Spesial", categoryLabel: "Kategori", rewardTypeLabel: "Jenis Hadiah", fixedReward: "Jumlah Tetap", percentageReward: "Persentase Tagihan", rewardAmountLabel: "Jumlah Hadiah Promotor (dalam USD)", avgBillLabel: "Rata-rata Tagihan (dalam USD)", percentLabel: "Persentase Hadiah (%)", conditionsLabel: "Kondisi / Deskripsi", conditionsPlaceholder: "Jelaskan persyaratan konversi (misalnya, pembelian hidangan utama diperlukan)", createBtn: "Buat Penawaran", cancelBtn: "Batal", codeError: "Kode rujukan aktif tidak ditemukan atau kedaluwarsa", offerError: "Penawaran tidak ditemukan", balanceError: "Saldo cadangan tidak mencukupi untuk membayar hadiah", balanceErrorCreate: "Saldo cadangan tidak mencukupi untuk membuat penawaran ini. Silakan setor dana terlebih dahulu.", successPrefix: "Rujukan dikonfirmasi!", depositSuccess: "berhasil ditambahkan ke saldo cadangan Anda.", loading: "Memuat Panel Bisnis...", recentTransactions: "Transaksi Terakhir",
    categories: { restaurant: "Restoran", nightlife: "Hiburan Malam", real_estate: "Real Estat & Vila", beauty: "Kecantikan & Spa", fitness: "Kebugaran & Olahraga", retail: "Eceran", activity: "Aktivitas", services: "Layanan" }
  },
  zh: {
    venue: "商户经理", exit: "退出", settings: "设置 ⚙️", balanceLabel: "活跃准备金余额", depositBtn: "充值 $100", reserveNote: "🔒 准备金保护已激活：如果奖励金额超过当前准备金余额，优惠将自动停用。", attributeTitle: "验证推荐码", verifyBtn: "核销并支付", offersTitle: "您的活跃优惠", rewardLabel: "奖励", statusActive: "活跃", statusPaused: "已暂停 (余额不足)", noOffers: "暂无优惠活动", noTransactions: "暂无交易记录", createTitle: "创建新优惠", offerTitleLabel: "优惠标题", offerTitlePlaceholder: "例如：特别促销", categoryLabel: "类别", rewardTypeLabel: "奖励类型", fixedReward: "固定金额", percentageReward: "账单百分比", rewardAmountLabel: "推广员奖励金额 (USD)", avgBillLabel: "平均账单金额 (USD)", percentLabel: "奖励百分比 (%)", conditionsLabel: "条款与描述", conditionsPlaceholder: "描述核销条件 (例如：必须点主菜)", createBtn: "创建优惠", cancelBtn: "取消", codeError: "未找到活跃推荐码或已过期", offerError: "优惠未找到", balanceError: "准备金余额不足，无法支付奖励", balanceErrorCreate: "准备金余额不足，无法创建优惠。请先充值。", successPrefix: "推荐核销成功！", depositSuccess: "已成功存入您的准备金余额。", loading: "正在加载商户门户...", recentTransactions: "最近的交易",
    categories: { restaurant: "餐厅", nightlife: "夜生活", real_estate: "房地产与别墅", beauty: "美容与水疗", fitness: "健身与体育", retail: "零售", activity: "活动", services: "服务" }
  },
  es: {
    venue: "Gerente del Lugar", exit: "Salir", settings: "Ajustes ⚙️", balanceLabel: "Saldo de Reserva Activo", depositBtn: "Depositar $100", reserveNote: "🔒 Protección de Reserva Activa: Las ofertas se desactivarán automáticamente si la recompensa excede el saldo de reserva.", attributeTitle: "Atribuir Código de Referido", verifyBtn: "Verificar y Pagar", offersTitle: "Sus Ofertas Activas", rewardLabel: "Recompensa", statusActive: "ACTIVO", statusPaused: "PAUSADO (Saldo Bajo)", noOffers: "Aún no hay ofertas creadas", noTransactions: "Aún no hay transacciones registradas", createTitle: "Crear Nueva Oferta", offerTitleLabel: "Título de la Oferta", offerTitlePlaceholder: "ej. Promoción Especial", categoryLabel: "Categoría", rewardTypeLabel: "Tipo de Recompensa", fixedReward: "Monto Fijo", percentageReward: "Porcentaje de la Cuenta", rewardAmountLabel: "Monto de Recompensa al Promotor (en USD)", avgBillLabel: "Cuenta Promedio (en USD)", percentLabel: "Porcentaje de Recompensa (%)", conditionsLabel: "Condiciones / Descripción", conditionsPlaceholder: "Describa los términos (ej. se requiere plato principal)", createBtn: "Crear Oferta", cancelBtn: "Cancelar", codeError: "Código de referido no encontrado o expirado", offerError: "Oferta no encontrada", balanceError: "Saldo de reserva insuficiente para pagar la recompensa", balanceErrorCreate: "Saldo de reserva insuficiente para crear la oferta. Deposite fondos primero.", successPrefix: "¡Referido confirmado!", depositSuccess: "añadido con éxito a su saldo de reserva.", loading: "Cargando Portal de Negocios...", recentTransactions: "Transacciones Recientes",
    categories: { restaurant: "Restaurante", nightlife: "Vida nocturna", real_estate: "Bienes raíces y villas", beauty: "Belleza y spa", fitness: "Fitness y deportes", retail: "Minorista", activity: "Actividades", services: "Servicios" }
  },
  de: {
    venue: "Veranstaltungsort-Manager", exit: "Beenden", settings: "Einstellungen ⚙️", balanceLabel: "Aktives Reserveguthaben", depositBtn: "100 $ einzahlen", reserveNote: "🔒 Reserveschutz aktiv: Angebote werden automatisch deaktiviert, wenn die Belohnung Ihr Guthaben übersteigt.", attributeTitle: "Empfehlungscode zuordnen", verifyBtn: "Verifizieren & Bezahlen", offersTitle: "Ihre aktiven Angebote", rewardLabel: "Belohnung", statusActive: "AKTIV", statusPaused: "PAUSIERT (Wenig Guthaben)", noOffers: "Noch keine Angebote erstellt", noTransactions: "Noch keine Transaktionen aufgezeichnet", createTitle: "Neues Angebot erstellen", offerTitleLabel: "Angebotstitel", offerTitlePlaceholder: "z. B. Sonderaktion", categoryLabel: "Kategorie", rewardTypeLabel: "Belohnungstyp", fixedReward: "Fester Betrag", percentageReward: "Prozent der Rechnung", rewardAmountLabel: "Promoter-Belohnungsbetrag (in USD)", avgBillLabel: "Durchschnittliche Rechnung (in USD)", percentLabel: "Belohnungsprozentsatz (%)", conditionsLabel: "Bedingungen / Beschreibung", conditionsPlaceholder: "Bedingungen beschreiben (z. B. Hauptgericht erforderlich)", createBtn: "Angebot erstellen", cancelBtn: "Abbrechen", codeError: "Aktiver Empfehlungscode nicht gefunden oder abgelaufen", offerError: "Angebot nicht gefunden", balanceError: "Ungenügendes Reserveguthaben für die Belohnung", balanceErrorCreate: "Ungenügendes Reserveguthaben für dieses Angebot. Bitte zuerst einzahlen.", successPrefix: "Empfehlung bestätigt!", depositSuccess: "erfolgreich Ihrem Reserveguthaben gutgeschrieben.", loading: "Business-Portal wird geladen...", recentTransactions: "Letzte Transaktionen",
    categories: { restaurant: "Restaurant", nightlife: "Nachtleben", real_estate: "Immobilien & Villen", beauty: "Schönheit & Spa", fitness: "Fitness & Sport", retail: "Einzelhandel", activity: "Aktivitäten", services: "Dienstleistungen" }
  },
  fr: {
    venue: "Gérant de l'Établissement", exit: "Quitter", settings: "Paramètres ⚙️", balanceLabel: "Solde de Réserve Actif", depositBtn: "Déposer 100 $", reserveNote: "🔒 Protection de Réserve Active : Les offres seront désactivées si la récompense dépasse le solde.", attributeTitle: "Attribuer Code de Parrainage", verifyBtn: "Vérifier & Payer", offersTitle: "Vos Offres Actives", rewardLabel: "Récompense", statusActive: "ACTIF", statusPaused: "PAUSÉ (Solde Bas)", noOffers: "Aucune offre créée", noTransactions: "Aucune transaction enregistrée pour le moment", createTitle: "Créer une Offre", offerTitleLabel: "Titre de l'Offre", offerTitlePlaceholder: "ex. Promotion Spéciale", categoryLabel: "Catégorie", rewardTypeLabel: "Type de Récompense", fixedReward: "Montant Fixe", percentageReward: "Pourcentage de l'Addition", rewardAmountLabel: "Montant de Récompense (en USD)", avgBillLabel: "Addition Moyenne (en USD)", percentLabel: "Pourcentage de Récompensa (%)", conditionsLabel: "Conditions / Description", conditionsPlaceholder: "Décrivez les termes (ex. plat principal requis)", createBtn: "Créer l'Offre", cancelBtn: "Annuler", codeError: "Code de parrainage non trouvé ou expiré", offerError: "Offre non trouvée", balanceError: "Solde de réserve insuffisant pour payer la récompense", balanceErrorCreate: "Solde de réserve insuffisant pour créer l'offre. Veuillez déposer des fonds.", successPrefix: "Parrainage confirmé !", depositSuccess: "ajouté avec succès à votre solde de réserve.", loading: "Chargement du Portail Entreprise...", recentTransactions: "Transactions Récentes",
    categories: { restaurant: "Restaurant", nightlife: "Vie nocturne", real_estate: "Immobilier & Villas", beauty: "Beauté & Spa", fitness: "Fitness & Sports", retail: "Commerce de détail", activity: "Activités", services: "Services" }
  },
  ja: {
    venue: "会場マネージャー", exit: "終了", settings: "設定 ⚙️", balanceLabel: "アクティブな準備金残高", depositBtn: "$100をデポジット", reserveNote: "🔒 準備金保護がアクティブです：報酬額が現在の準備金残高を超えると、オファーは自動的に無効になります。", attributeTitle: "紹介コードを適用", verifyBtn: "確認して支払う", offersTitle: "アクティブなオファー", rewardLabel: "報酬", statusActive: "アクティブ", statusPaused: "一時停止（残高不足）", noOffers: "まだオファーが作成されていません", noTransactions: "まだ取引が記録されていません", createTitle: "新しいオファーを作成", offerTitleLabel: "オファーのタイトル", offerTitlePlaceholder: "例: 特別プロモーション", categoryLabel: "カテゴリー", rewardTypeLabel: "報酬タイプ", fixedReward: "固定額", percentageReward: "請求額のパーセンテージ", rewardAmountLabel: "プロモーター報酬額（USD）", avgBillLabel: "平均請求額（USD）", percentLabel: "報酬パーセンテージ（％）", conditionsLabel: "条件/説明", conditionsPlaceholder: "変換条件を説明してください（例：メインディッシュの購入が必要）", createBtn: "オファーを作成", cancelBtn: "キャンセル", codeError: "アクティブな紹介コードが見つからないか、期限切れです", offerError: "オファーが見つかりません", balanceError: "報酬を支払うための準備金残高が不足しています", balanceErrorCreate: "報酬をカバーするための準備金残高が不足しています。先に資金を預けてください。", successPrefix: "紹介が確認されました！", depositSuccess: "準備金残高に正常に追加されました。", loading: "ビジネス・ポータルを読み込み中...", recentTransactions: "最近の取引",
    categories: { restaurant: "レストラン", nightlife: "ナイトライフ", real_estate: "不動産＆ヴィラ", beauty: "ビューティー＆スパ", fitness: "フィットネス＆スポーツ", retail: "小売", activity: "アクティビティ", services: "サービス" }
  },
  ar: {
    venue: "مدير المكان", exit: "خروج", settings: "الإعدادات ⚙️", balanceLabel: "رصيد الاحتياطي النشط", depositBtn: "إيداع 100 دولار", reserveNote: "🔒 حماية الاحتياطي نشطة: سيتم إلغاء تنشيط العروض تلقائيًا إذا تجاوز مبلغ المكافأة رصيد الاحتياطي الحالي.", attributeTitle: "إدخال رمز الإحالة", verifyBtn: "التحقق والدفع", offersTitle: "عروضك النشطة", rewardLabel: "مكافأة", statusActive: "نشط", statusPaused: "متوقف (رصيد منخفض)", noOffers: "لم يتم إنشاء عروض حتى الآن", noTransactions: "لم يتم تسجيل معاملات حتى الآن", createTitle: "إنشاء عرض جديد", offerTitleLabel: "عنوان العرض", offerTitlePlaceholder: "مثال: ترويج خاص", categoryLabel: "فئة", rewardTypeLabel: "نوع المكافأة", fixedReward: "مبلغ ثابت", percentageReward: "نسبة من الفاتورة", rewardAmountLabel: "مبلغ مكافأة المروج (بالدولار الأمريكي)", avgBillLabel: "متوسط الفاتورة (بالدولار الأمريكي)", percentLabel: "نسبة المكافأة (%)", conditionsLabel: "الشروط / الوصف", conditionsPlaceholder: "صف شروط التحويل (مثال: شراء الطبق الرئيسي مطلوب)", createBtn: "إنشاء العرض", cancelBtn: "إلغاء", codeError: "رمز الإحالة النشط غير موجود أو منتهي الصلاحية", offerError: "العرض غير موجود", balanceError: "رصيد الاحتياطي غير كافٍ لدفع المكافأة", balanceErrorCreate: "رصيد الاحتياطي غير كافٍ لتغطية المكافأة. يرجى إيداع الأموال أولاً.", successPrefix: "تم تأكيد الإحالة!", depositSuccess: "تم إضافته بنجاح إلى رصيد الاحتياطي الخاص بك.", loading: "جارٍ تحميل بوابة الأعمال...", recentTransactions: "المعاملات الأخيرة",
    categories: { restaurant: "مطعم", nightlife: "حياة الليل", real_estate: "عقارات وفلل", beauty: "تجميل وسبا", fitness: "لياقة ورياضة", retail: "تجزئة", activity: "أنشطة", services: "خدمات" }
  },
  pt: {
    venue: "Gestor de Local", exit: "Sair", settings: "Configurações ⚙️", balanceLabel: "Saldo de Reserva Ativo", depositBtn: "Depositar $100", reserveNote: "🔒 Proteção de Reserva Ativa: As ofertas serão desativadas automaticamente se o montante da recompensa exceder o saldo atual da sua reserva.", attributeTitle: "Atribuir Código de Referência", verifyBtn: "Verificar e Pagar", offersTitle: "As Suas Ofertas Ativas", rewardLabel: "Recompensa", statusActive: "ATIVO", statusPaused: "PAUSADO (Saldo Baixo)", noOffers: "Ainda não foram criadas ofertas", noTransactions: "Ainda não há transações registadas", createTitle: "Criar Nova Oferta", offerTitleLabel: "Título da Oferta", offerTitlePlaceholder: "ex: Promoção Especial", categoryLabel: "Categoria", rewardTypeLabel: "Tipo de Recompensa", fixedReward: "Montante Fixo", percentageReward: "Percentagem da Conta", rewardAmountLabel: "Montante de Recompensa do Promotor (em USD)", avgBillLabel: "Conta Média (em USD)", percentLabel: "Percentagem de Recompensa (%)", conditionsLabel: "Condições / Descrição", conditionsPlaceholder: "Descreva os termos de conversão (ex: é obrigatória a compra de um prato principal)", createBtn: "Criar Oferta", cancelBtn: "Cancelar", codeError: "Código de referência ativo não encontrado ou expirado", offerError: "Oferta não encontrada", balanceError: "Saldo de reserva insuficiente para pagar a recompensa", balanceErrorCreate: "Saldo de reserva insuficiente para cobrir a recompensa. Por favor, deposite fundos primeiro.", successPrefix: "Referência confirmada!", depositSuccess: "adicionado com sucesso ao seu saldo de reserva.", loading: "A carregar Portal de Negócios...", recentTransactions: "Transações Recentes",
    categories: { restaurant: "Restaurante", nightlife: "Vida Noturna", real_estate: "Imobiliária e Vilas", beauty: "Beleza e Spa", fitness: "Fitness e Desporto", retail: "Retalho", activity: "Atividades", services: "Serviços" }
  },
  hi: {
    venue: "स्थान प्रबंधक", exit: "बाहर निकलें", settings: "सेटिंग्स ⚙️", balanceLabel: "सक्रिय रिजर्व बैलेंस", depositBtn: "$100 जमा करें", reserveNote: "🔒 रिजर्व सुरक्षा सक्रिय: यदि इनाम राशि आपके वर्तमान रिजर्व बैलेंस से अधिक है, तो ऑफ़र स्वचालित रूप से निष्क्रिय हो जाएंगे।", attributeTitle: "रेफरल कोड एट्रिब्यूट करें", verifyBtn: "सत्यापित करें और भुगतान करें", offersTitle: "आपके सक्रिय ऑफ़र", rewardLabel: "इनाम", statusActive: "सक्रिय", statusPaused: "रुका हुआ (कम बैलेंस)", noOffers: "अभी तक कोई ऑफ़र नहीं बनाया गया है", noTransactions: "अभी तक कोई लेनदेन रिकॉर्ड नहीं किया गया है", createTitle: "नया ऑफ़र बनाएं", offerTitleLabel: "ऑफ़र शीर्षक", offerTitlePlaceholder: "उदा. विशेष पदोन्नति", categoryLabel: "श्रेणी", rewardTypeLabel: "इनाम का प्रकार", fixedReward: "निश्चित राशि", percentageReward: "बिल का प्रतिशत", rewardAmountLabel: "प्रमोटर इनाम राशि (USD में)", avgBillLabel: "औसत बिल (USD में)", percentLabel: "इनाम प्रतिशत (%)", conditionsLabel: "शर्तें / विवरण", conditionsPlaceholder: "रूपांतरण शर्तों का वर्णन करें (उदा. मुख्य पकवान की खरीद आवश्यक है)", createBtn: "ऑफ़र बनाएं", cancelBtn: "रद्द करें", codeError: "सक्रिय रेफरल कोड नहीं मिला या समाप्त हो गया है", offerError: "ऑफ़र नहीं मिला", balanceError: "इनाम का भुगतान करने के लिए अपर्याप्त रिजर्व बैलेंस", balanceErrorCreate: "इनाम को कवर करने के लिए अपर्याप्त रिजर्व बैलेंस। कृपया पहले धनराशि जमा करें।", successPrefix: "रेफरल की पुष्टि हो गई!", depositSuccess: "आपके रिजर्व बैलेंस में सफलतापूर्वक जोड़ा गया।", loading: "बिजनेस पोर्टल लोड हो रहा है...", recentTransactions: "हालिया लेनदेन",
    categories: { restaurant: "रेस्तरां", nightlife: "नाइटलाइफ़", real_estate: "रियल एस्टेट और विला", beauty: "ब्यूटी एंड स्पा", fitness: "फिटनेस और खेल", retail: "रिटेल", activity: "गतिविधियां", services: "सेवाएं" }
  }
};


function replaceTranslations(filePath, langObj) {
  let content = fs.readFileSync(filePath, 'utf8');
  
  const startRegex = new RegExp("const translations(?:[^=]*)=\\s*\\{");
  const startMatch = content.match(startRegex);
  
  if (!startMatch) {
    console.log('Translations not found in ' + filePath);
    return;
  }
  
  const startIdx = startMatch.index;
  let endIdx = -1;
  let braceCount = 0;
  let foundFirstBrace = false;
  
  for (let i = startIdx; i < content.length; i++) {
    if (content[i] === '{') {
      braceCount++;
      foundFirstBrace = true;
    } else if (content[i] === '}') {
      braceCount--;
    }
    
    if (foundFirstBrace && braceCount === 0) {
      endIdx = i;
      break;
    }
  }
  
  if (endIdx === -1) {
    console.log('Could not find end of translations in ' + filePath);
    return;
  }
  
  let formattedObj = JSON.stringify(langObj, null, 2).replace(/"([^"]+)":/g, '$1:');
  const newBlock = `const translations = ${formattedObj};`;
  
  content = content.substring(0, startIdx) + newBlock + content.substring(endIdx + 1);
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('Updated ' + filePath);
}

replaceTranslations('src/app/partner/settings/page.tsx', partnerSettingsLangs);
replaceTranslations('src/app/onboarding/page.tsx', onboardingLangs);
replaceTranslations('src/app/onboarding/page_complex.tsx', onboardingLangs);
replaceTranslations('src/app/business/page.tsx', businessLangs);
